jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t image .
        - docker save -o images.tar image
      workspaces:
        create:
          name: docker_cache
          paths:
            images.tar
    - stage: test image
      script:
        - docker load -i images.tar
        - docker run image
      workspaces:
        use: docker_cache

notifications:
  email: false
