cache:
  directories:
    - docker_images

before_install:
  - docker load -i docker_images/images.tar || true

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

jobs:
  include:
    - stage: build docker image
      script: docker build -t image .
    - stage: test image
      script: docker run image

notifications:
  email: false